#!/bin/bash

# 23,27 s/^/#/g
# 23,27 s/^#//g

pw_mtag='/mtag_pipeline'

overlap="overlap"
N=${#}
trait=`echo ${*} | sed 's/ /_/g'`
esumstat=`echo ${*} | sed 's/ /\n/g' | awk '{print "./"$0".input"}' | tr "\n" "," | rev | cut -c 2- | rev`
mtag_out="./zzz.mtag.${N}.${trait}"

# input
echo ${*} | sed 's/ /\n/g' | while read disease_name
do
	if [ ! -f ${disease_name}.input ]; then
		cat ${disease_name}.posma | sed '1d' | awk '{print $1,$2,$3,$4,$5,$6,$7,$8,$7/$8,$9,$10}' | sed '1i CHR POS SNP A1 A2 EAF BETA SE Z P N' > ${disease_name}.input
	fi
done

# mtag
python2 /mtag-master/mtag.py \
	--sumstats ${esumstat} \
	--chr_name CHR --bpos_name POS --snp_name SNP --a1_name A1 --a2_name A2 --eaf_name EAF --z_name Z --n_name N \
	--out ${mtag_out} \
	--stream_stdout

# mtag.posma mtag.ma
Sample_Size_line=`cat ${mtag_out}.log | awk '{print FNR"\t"$0}' | grep "GWAS mean chi" | grep "MTAG mean chi" | cut -f1`
Sample_Size_mtag=`cat ${mtag_out}.log | sed "1,${Sample_Size_line}d" | head -1 | awk '{print $NF}'`
cat ${mtag_out}_trait_1.txt | sed '1d' | \
	awk 'BEGIN{FS=OFS="\t"}{print $2*1,$3*1,$1,$4,$5,$8,$9,$10,$12,"'"${Sample_Size_mtag}"'"}' | \
	sed '1i CHR\tPOS\tSNP\tA1\tA2\tEAF\tBETA\tSE\tP\tN' > ${1}.mtag.overlap
python ${pw_mtag}/mtag_fusion.py ${1}.posma ${1}.mtag.overlap ${1}.mtag.posma
cat ${1}.mtag.posma | cut -f3- > ${1}.mtag.ma

#echo "overlap  : ${overlap} "
#echo "N        : ${N}       "
#echo "trait    : ${trait}   "
#echo "esumstat : ${esumstat}"
#echo "mtag_out : ${mtag_out}"
