#!/bin/bash

echo "##############################################"
echo "#                                            #"
echo "#                   MTAG                     #"
echo "#                                            #"
echo "#  2024.12.30     Shi Yao & Xin Ke & Hao Wu  #"
echo "#                                            #"
echo "##############################################"
echo ""

echo "----------------------------------------------"
echo ""
echo "[mtag_fusion]"
echo ">>> mtag_fusion [GWAS_1] [GWAS_2] ... [GWAS_n]"
echo ""
echo "----------------------------------------------"
echo ""
echo "Calculate MTAG, input suffix of file:  [posma]"
echo ">>> CHR POS SNP A1 A2 EAF BETA SE P N"
echo ""
echo "----------------------------------------------"
echo ""
echo "[MTAG, Multi-Trait Analysis of GWAS]"
echo ">>> https://github.com/omeed-maghzian/mtag.git"
echo ""
echo "----------------------------------------------"
